spring:
  flyway:
    enabled: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/flyway_test?autoreconnect=true"
    username: ${db_username}
    password: ${db_pass}
